#include <iostream>
#include <vector>

/*
    ============
    === EASY ===
    ============

    ===========================
    389) Find the Difference
    ===========================

    ============
    Description:
    ============

    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more
    letter at a random position.

    Return the letter that was added to t.

    =====================================================
    FUNCTION: char findTheDifference(string s, string t);
    =====================================================

    ==========================================================================
    ================================ EXAMPLES ================================
    ==========================================================================

    --- Example 1 ---
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

    --- Example 2 ---
    Input: s = "", t = "y"
    Output: "y"

    --- Example 3 ---
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.


    *** Constraints ***
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.

*/

/*
    ------------
    --- IDEA ---
    ------------

    Self-explanatory.

*/

/* Time  Beats: 48.37% */
/* Space Beats: 21.75% */

/* Time  Complexity: O(n) */
/* Space Complexity: O(1) */
class Solution {
public:
    char findTheDifference(std::string s, std::string t)
    {
        std::vector<int> letters(26, 0);

        for (const char& chr : s)
            letters[chr - 'a']++;

        for (const char& chr : t)
        {
            if (letters[chr - 'a'] == 0)
                return chr;

            letters[chr - 'a']--;
        }

        return 'x'; // This will never be returned
    }
};
